#!/usr/bin/env python3
"""Generate schema/<category>.schema.json (JSON Schema draft 2020-12) from
scripts/validate.py's required lists, type maps, and enum registry.

NEVER hand-edit the emitted files — regenerate with this script (CI enforces
sync the same way it does for the controller_boards/psu aggregates).

Usage:
    python3 scripts/gen_schema.py             # (re)write schema/*.schema.json
    python3 scripts/gen_schema.py --validate  # jsonschema-check every YAML
                                              # entry against its schema
"""
import glob
import importlib.util
import json
import os
import sys

ROOT = os.path.join(os.path.dirname(__file__), "..")
SCHEMA_DIR = os.path.join(ROOT, "schema")

_spec = importlib.util.spec_from_file_location(
    "validate", os.path.join(os.path.dirname(__file__), "validate.py"))
assert _spec is not None and _spec.loader is not None
validate = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(validate)

JSON_TYPES = {
    "string": "string",
    "number": "number",
    "integer": "integer",
    "bool": "boolean",
    "list": "array",
}


def build_schema(category):
    required = validate.CATEGORIES[category]
    field_types = validate.FIELD_TYPES[category]
    enums = validate.ENUM_FIELDS.get(category, {})

    properties = {}
    for field, t in field_types.items():
        if field in enums:
            allowed, null_ok = enums[field]
            values = sorted(allowed)
            if null_ok:
                values = values + [None]
            properties[field] = {"enum": values}
        else:
            # null always means unknown and is allowed for any non-enum field
            properties[field] = {"type": [JSON_TYPES[t], "null"]}

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": (
            "https://raw.githubusercontent.com/BakedBean3D/"
            f"3d-printer-hardware-database/main/schema/{category}.schema.json"
        ),
        "title": f"{category} file",
        "description": (
            "Generated by scripts/gen_schema.py from scripts/validate.py — "
            "do not hand-edit. Structural schema only; validate.py adds "
            "physics/plausibility checks JSON Schema cannot express."
        ),
        "type": "array",
        "items": {
            "type": "object",
            "required": list(required),
            "properties": properties,
        },
    }


def generate():
    os.makedirs(SCHEMA_DIR, exist_ok=True)
    for category in validate.CATEGORIES:
        path = os.path.join(SCHEMA_DIR, f"{category}.schema.json")
        with open(path, "w") as f:
            json.dump(build_schema(category), f, indent=2, sort_keys=False)
            f.write("\n")
    print(f"{len(validate.CATEGORIES)} schemas -> schema/")


def check_data():
    import jsonschema
    import yaml

    errors = 0
    for category in validate.CATEGORIES:
        schema = build_schema(category)
        v = jsonschema.Draft202012Validator(schema)
        for path in sorted(glob.glob(os.path.join(ROOT, category, "*.yaml"))):
            with open(path) as f:
                data = yaml.safe_load(f) or []
            for err in v.iter_errors(data):
                loc = "/".join(str(p) for p in err.absolute_path)
                print(f"  SCHEMA: {path}[{loc}]: {err.message}")
                errors += 1
    print(f"{'PASSED' if errors == 0 else 'FAILED'} — {errors} schema errors")
    return 0 if errors == 0 else 1


if __name__ == "__main__":
    if "--validate" in sys.argv:
        sys.exit(check_data())
    generate()
